---
title: "Methods"
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 1
---

```{r, include=FALSE}
source("R/base.R")
source("R/helpers.R")
source("R/theme.R")
```

# Team structures

```{r team-structures, fig.width=2}
diagram_graphviz("team-structures", package = "evoteams")
```

# Labor hours and calendar hours

```{r time-plot, fig.width=4, fig.height=4}
diachronic <- data_frame(
  strategy = "diachronic",
  calendar_hours = 0:100,
  labor_hours = calendar_hours
)

synchronic <- data_frame(
  strategy = "synchronic",
  calendar_hours = 0:50,
  labor_hours = calendar_hours * 2
)

time <- rbind(diachronic, synchronic)

axis_breaks <- c(0, 50, 100)
axis_labels <- axis_breaks

(gg_time <- ggplot(time, aes(calendar_hours, labor_hours)) +
  geom_line(aes(color = strategy), size = 1.2) +
  scale_x_continuous("calendar hours", breaks = axis_breaks, labels = axis_labels) +
  scale_y_continuous("labor hours", breaks = axis_breaks, labels = axis_labels) +
  scale_color_strategy +
  guides(color = guide_legend(reverse = TRUE)) +
  base_theme +
  theme(legend.position = "top"))
```

# Ability as vision

```{r, fig.keep='last', fig.width=6, fig.height=6}
ability <- data_frame(vision = 1:9)

(gg_single_dimension <- ggplot(ability) +
  aes(vision, vision) +
  geom_bar(aes(alpha = vision), stat = "identity", fill = theme_colors[["blue"]]) +
  scale_x_continuous("", breaks = NULL) +
  scale_y_continuous("vision", breaks = 1:9) +
  scale_alpha_continuous(range = c(0.5, 1.0)) +
  guides(alpha = "none") +
  coord_cartesian(xlim = c(1, 9.2), ylim = c(0, 9.6)) +
  base_theme +
  theme(
    panel.grid.minor.y = element_blank()
  ) +
  ggtitle("Vision in a single dimension")
)

teams <- get_experiment_data("differing-skills") %>%
  get_team_info() %>%
  gather(dimension, value, -c(team, player, team_id)) %>%
  recode_team() %>%
  select(-team)

legend_text <- data_frame(
  team_label_rev = factor(0, levels = 0:4),
  player = 1,
  value = c(0.1, 0.1),
  dimension = c("vision_x", "vision_y"),
  label = c("vision x", "vision y")
)

dodge_width <- position_dodge(width = 0.9)

tradeoffs_plot <- ggplot() +
  aes(x = player, y = value, group = dimension) +
  geom_bar(aes(fill = team_label_rev, alpha = dimension),
           stat = "identity", position = dodge_width) +
  facet_wrap("team_label_rev", nrow = 1) +
  geom_text(aes(label = label), data = legend_text, position = dodge_width,
            angle = 90, vjust = 0.5, hjust = 0) +
  scale_x_continuous(breaks = c(1, 2)) +
  scale_y_continuous("vision", breaks = 1:10, expand = c(0, 0)) +
  scale_fill_brewer(palette = "Set2") +
  scale_alpha_manual(values = c(0.9, 0.5)) +
  coord_cartesian(ylim = c(0, 9)) +
  base_theme +
  theme(
    legend.position = "none",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank()
  )

(gg_two_dimensions <- (tradeoffs_plot %+% filter(teams, player == 1)) +
  scale_x_continuous("", labels = NULL) +
  theme(strip.text = element_blank()) +
  labs(title = "Vision in two dimensions"))

(gg_differing_skills <- (tradeoffs_plot %+% teams) +
  labs(title = "Two person teams varying in vision distribution"))

grid.arrange(
  arrangeGrob(gg_single_dimension, gg_two_dimensions, nrow = 1),
  gg_differing_skills,
  ncol = 1
)
```

# Vision and search areas

```{r, fig.width=8, fig.height=2}
# Vision of 1 gives a visible range of 3 (from -1 to 1)
visible_range <- function(vision) vision * 2 + 1

# Vision in two dimensions is a search area
calculate_search_area <- function(vision_x, vision_y) {
  search_area <- visible_range(vision_x) * visible_range(vision_y)
  return(search_area)
}

search_areas <- data_frame(
  vision_x = 5:1,
  vision_y = 5:9,
  search_area = calculate_search_area(vision_x, vision_y)
)

diachronic_team_search_areas <- search_areas %>%
  mutate(
    strategy = "diachronic",
    team_label_rev = factor(0:4)
  )

synchronic_team_search_areas <- data_frame(
  vision_x = 10, vision_y = 10,
  search_area = calculate_search_area(vision_x, vision_y),
  strategy = "synchronic",
  agg_func = "sum"
)

search_areas_by_strategy <- bind_rows(diachronic_team_search_areas,
                                      synchronic_team_search_areas) %>%
  mutate(vision_x_range = visible_range(vision_x),
         vision_y_range = visible_range(vision_y))

gg_search_areas <- ggplot() +
  aes(x = 0, y = 0, width = vision_y_range, height = vision_x_range,
      fill = team_label_rev) +
  geom_tile() +
  scale_x_continuous("vision x", labels = NULL) +
  scale_y_continuous("vision y", labels = NULL) +
  scale_fill_brewer(palette = "Set2", guide = "none") +
  coord_cartesian(xlim = c(-10, 10), ylim = c(-10, 10)) +
  facet_wrap("team_label_rev", nrow = 1, scales = "fixed") +
  base_theme +
  theme(strip.text = element_blank())
  
(gg_search_rects <- (gg_search_areas %+% filter(search_areas_by_strategy, strategy == "diachronic")))
```

```{r}
search_areas_by_strategy %<>%
  arrange(vision_y) %>%
  mutate(
    visions = paste0("(", vision_x, ",", vision_y, ")"),
    visions_f = factor(visions, levels = visions)
  )

ggplot(search_areas_by_strategy) +
  aes(visions_f, search_area, fill = visions_f) +
  geom_bar(stat = "identity") +
  annotate("text", x = 6, y = 10, label = "all synchronic teams",
           hjust = -0.1, angle = 90) +
  scale_x_discrete("(vision x, vision y)") +
  scale_y_continuous("search area") +
  scale_fill_brewer(palette = "Set2", guide = "none") +
  base_theme
```

# Landscapes

## Simple hill

```{r simple-hill}
limits <- -100:100
z <- expand.grid(x = limits, y = limits) %>%
  mutate(z = -x^2 - y^2) %>%
  spread(y, z)
z$x <- NULL  # bug! dplyr::select(-x) doesn't work
z <- as.matrix(z)

plot_ly(x = limits, y = limits, z = z) %>%
  add_surface()
```
