---
title: "Experiments"
output:
  html_document:
    theme: flatly
    toc: true
    toc_depth: 1
---

```{r config, include=FALSE}
library(knitr)

fig_width <- 6
fig_height <- 4

opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  warning = FALSE,
  fig.path = "figs/",
  fig.width = fig_width,
  fig.height = fig_height,
  cache = TRUE,
  cache.path = ".cache/"
)

read_chunk("R/setup.R")
```

```{r setup, include=FALSE}
```

# Identical teammates

```{r, fig.keep="last"}
data("identical_team")

(gg_identical_team_timeline <- ggplot(identical_team) +
  aes(time, fitness_pct, color = strategy) +
  geom_line(stat = "summary", fun.y = "mean", size = 1.2) +
  scale_x_continuous("calendar hours") +
  scale_y_continuous("fitness", labels = scales::percent) +
  scale_color_manual(
    "strategy",
    labels = c("diachronic", "synchronic"),
    values = get_theme_color_values(c("blue", "green")),
    guide = guide_legend(reverse = TRUE)
  ) +
  base_theme +
  theme(legend.position = "top"))

max_fitness <- identical_team %>%
  group_by(sim_id, strategy) %>%
  summarize(fitness_pct = max(fitness_pct)) %>%
  recode_strategy()

(gg_identical_team_final_fitness <- ggplot(max_fitness) +
  aes(strategy_rev, fitness_pct) +
  geom_bar(aes(fill = strategy), stat = "summary", fun.y = "mean", alpha = 0.5) +
  geom_point(aes(color = strategy), alpha = 0.2,
             position = position_jitter(width = 0.2, height = 0.0)) +
  scale_x_strategy_rev +
  scale_y_fitness_pct +
  scale_color_manual(values = get_theme_color_values(c("blue", "green"))) +
  scale_fill_manual(values = get_theme_color_values(c("blue", "green"))) +
  base_theme +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank()))

grid.arrange(gg_identical_team_timeline, 
             gg_identical_team_final_fitness, nrow = 1)
```

```{r}
set.seed(782)
sample_sim_ids <- identical_team %>%
  filter(exp_id == 1) %>%
  group_by(strategy, starting_pos) %>%
  sample_n(1) %>%
  .$sim_id

random_walk_plot <- ggplot(identical_team %>% filter(exp_id == 1)) +
  aes(pos_x, pos_y, group = sim_id, color = strategy) +
  geom_path(alpha = 0.2) +
  annotate("point", x = 0, y = 0, shape = 4) +
  annotate("point", x = -127.3, y = -127.3, shape = 1) +
  coord_equal() +
  facet_wrap("strategy_rev") +
  scale_x_continuous("", labels = NULL) +
  scale_y_continuous("", labels = NULL) +
  scale_color_strategy +
  base_theme +
  theme(legend.position = "none")

random_walk_plot
```

# Differing skills

```{r, fig.width=10, fig.keep="last"}
data("differing_skills")

(gg_differing_skills_timeline <- ggplot(differing_skills) +
  aes(time, fitness_pct, alpha = team_label, color = strategy) +
  geom_line(stat = "summary", fun.y = "mean", size = 1.2) +
  scale_x_continuous("calendar hours") +
  scale_y_fitness_pct +
  scale_color_strategy +
  scale_alpha_team +
  guides(color = guide_legend(order = 1),
         alpha = guide_legend(order = 2)) +
  base_theme)

max_fitness <- differing_skills %>%
  group_by(sim_id, strategy, team_label) %>%
  summarize(fitness_pct = max(fitness_pct)) %>%
  recode_strategy()

dodge_width <- 0.9
team_dodge <- position_dodge(width = dodge_width)
sim_dodge <- position_jitterdodge(dodge.width = dodge_width, jitter.width = 0.4)
(gg_differing_skills_final_fitness <- ggplot(max_fitness) +
    aes(x = strategy, fitness_pct, alpha = team_label) +
    scale_y_fitness_pct +
    # geom_point(aes(color = strategy), position = sim_dodge) +
    geom_bar(aes(fill = strategy),
             stat = "summary", fun.y = "mean", position = team_dodge) +
    scale_alpha_team +
    scale_fill_strategy +
    guides(fill = "none") +
    base_theme +
    theme(panel.grid.major.x = element_blank()))

grid.arrange(gg_differing_skills_timeline,
             gg_differing_skills_final_fitness,
             nrow = 1)
```

```{r, fig.width = 8, fig.height = 5}
(random_walk_plot %+% filter(differing_skills, exp_id == 1)) +
  facet_grid(strategy ~ team_label_rev)
```

# Solo teams

```{r, fig.keep="last", fig.width=10}
data("solo_teams")

(gg_solo_teams_timeline <- ggplot(solo_teams) +
    aes(time, fitness_pct, alpha = team_label, color = strategy) +
    geom_line(stat = "summary", fun.y = "mean", size = 1.2) +
    scale_x_continuous("calendar hours") +
    scale_y_continuous("fitness", labels = scales::percent) +
    scale_color_manual("strategy", values = get_theme_color_values(c("blue", "green"))) +
    scale_alpha_team +
    guides(color = guide_legend(order = 1),
           alpha = guide_legend(order = 2)) +
    base_theme)

max_fitness <- solo_teams %>%
  group_by(sim_id, strategy, team_label) %>%
  summarize(fitness_pct = max(fitness_pct))

(gg_solo_teams_final_fitness <- (gg_differing_skills_final_fitness %+% max_fitness))

grid.arrange(gg_solo_teams_timeline, gg_solo_teams_final_fitness, nrow = 1)
```

# Number of exchanges

```{r}
data("alternating")

ggplot(alternating) +
  aes(time, fitness_pct, color = exchange_rate) +
  geom_line(stat = "summary", fun.y = "mean", size = 1.2) +
  scale_x_continuous("calendar hours") +
  scale_y_continuous("fitness", labels = scales::percent) +
  scale_color_brewer("exchanges", palette = "Set2", guide = guide_legend(reverse = TRUE)) +
  base_theme
```

# Aggregate functions

```{r}
ggplot(aggregate_fns) +
  aes(time, fitness_pct, color = aggregate_fn) +
  geom_line(stat = "summary", fun.y = "mean", size = 1.2) +
  scale_x_continuous("calendar hours") +
  scale_y_continuous("fitness", labels = scales::percent) +
  scale_color_brewer("aggregate function", palette = "Set2") +
  base_theme
```

# Variable feedback

```{r, fig.width = fig_width * 2}
feedback_trials_plot <- ggplot(variable_feedback) +
  aes(factor(strategy, levels = c("synchronic", "diachronic")), feedback, fill = strategy) +
  geom_bar(aes(alpha = factor(p_feedback, levels = c(0.1, 0.5, 1.0))),
           stat = "summary", fun.y = "sum", position = "dodge") +
  scale_x_discrete("strategy") +
  scale_y_continuous("feedback trials", labels = NULL) +
  scale_fill_manual(values = get_theme_color_values(c("blue", "green"))) +
  scale_alpha_discrete("prob feedback", labels = c("10%", "50%", "100%"), range = c(0.4, 1.0)) +
  base_theme

variable_feedback_plot <- ggplot(variable_feedback) +
  aes(time, fitness_pct, color = strategy, alpha = factor(p_feedback)) +
  geom_line(stat = "summary", fun.y = "mean", size = 1.2) +
  scale_x_continuous("calendar hours") +
  scale_y_continuous("fitness", labels = scales::percent) +
  scale_color_strategy +
  scale_alpha_discrete("prob feedback", labels = c("10%", "50%", "100%"), range = c(0.6, 1.0)) +
  guides(
    color = guide_legend(order = 1),
    alpha = guide_legend(order = 2, reverse = TRUE)
  ) +
  base_theme

grid.arrange(feedback_trials_plot, variable_feedback_plot, nrow = 1)
```
