```{r, include=FALSE}
source("R/base.R")
source("R/helpers.R")
source("R/theme.R")
```

```{r team-structures}
diagram_graphviz("team-structures", package = "evoteams")
```

```{r time-plot, fig.keep="none"}
diachronic <- data_frame(
  strategy = "diachronic",
  calendar_hours = 0:100,
  labor_hours = calendar_hours
)

synchronic <- data_frame(
  strategy = "synchronic",
  calendar_hours = 0:50,
  labor_hours = calendar_hours * 2
)

time <- rbind(diachronic, synchronic)

axis_breaks <- c(0, 50, 100)
axis_labels <- axis_breaks

(gg_time <- ggplot(time, aes(calendar_hours, labor_hours)) +
  geom_line(aes(color = strategy), size = 1.2) +
  scale_x_continuous("calendar hours", breaks = axis_breaks, labels = axis_labels) +
  scale_y_continuous("labor hours", breaks = axis_breaks, labels = axis_labels) +
  scale_color_strategy +
  base_theme +
  theme(legend.position = "top"))
```

```{r min-steps, fig.keep="none"}
start_radius <- 100
hyp_distance <- sqrt(2 * start_radius^2)
synchronic_max <- sqrt(2 * 10^2)
synchronic_calendar_hours <- 50
diachronic_max <- sqrt(2 * 5^2)
diachronic_calendar_hours <- 100

min_steps <- data_frame(
  strategy = c("synchronic", "diachronic"),
  labor_hours_per_calendar_hour = c(2, 1),
  calendar_hours_to_peak = c(
    (hyp_distance/synchronic_max),
    (hyp_distance/diachronic_max)
  ),
  labor_hours_to_peak = calendar_hours_to_peak * labor_hours_per_calendar_hour)

gg_min_steps <- ggplot(min_steps) +
  geom_bar(stat = "identity") +
  scale_fill_manual(values = get_theme_color_values(c("blue", "green"))) +
  base_theme +
  theme(legend.position = "none",
        panel.grid.major.x = element_blank())

(gg_min_calendar <- gg_min_steps +
  aes(strategy, calendar_hours_to_peak, fill = strategy) +
  scale_y_continuous("calendar hours to peak (minimum)",
                     breaks = c(0, 10, 20)))

(gg_min_labor <- gg_min_steps +
  aes(strategy, labor_hours_to_peak, fill = strategy) +
  scale_y_continuous("labor hours to peak (minimum)",
                     breaks = c(0, 10, 20)))
```

```{r, fig.width = fig_width * 2}
grid.arrange(gg_time, gg_min_calendar, gg_min_labor, nrow = 1)
```