---
title: "Mountain Climbers"
---

```{r, include=FALSE}
library(knitr)
opts_chunk$set(
  echo = FALSE,
  message = FALSE,
  fig.path = "figs/",
  cache = TRUE,
  cache.path = ".cache/"
)

library(tidyverse)
library(magrittr)

library(evoteams)
library(crotchet)
read_graphviz_chunk("team-structures", "evoteams")
```

```{r helper-functions, include=FALSE}
get_experiment_data <- function(experiment) {
  file.path("experiments", paste0(experiment, ".csv")) %>%
    read_csv() %>%
    recode_fitness_as_pct()
}

recode_fitness_as_pct <- function(frame) {
  mutate(frame, fitness_pct = 1 - fitness/min(fitness))
}

extract_position <- function(frame) {
  pos <- map(frame$pos, jsonlite::fromJSON)
  get_coord <- function(n) {
    map(pos, function(x) x[[n]]) %>%
      unlist()
  }
  frame$pos_x <- get_coord(1)
  frame$pos_y <- get_coord(2)
  frame
}

recode_team <- function(frame) {
  teams <- get_team_info(frame)

  # Order teams from most disjoint to least
  team_levels <- letters[5:1]
  team_map <- teams %>%
    select(team, team_id) %>%
    unique() %>%
    arrange(team_id) %>%
    mutate(
      team_label = factor(team_id, levels = team_levels),
      team_label_rev = factor(team_id, levels = rev(team_levels),
                              labels = 0:4)
    )
  
  left_join(frame, team_map)
}

get_team_info <- function(frame) {
  unique(frame$team) %>%
    map(function(team) {
      data <- jsonlite::fromJSON(team)
      data$players %>%
        mutate(
          player = 1:n(),
          team_id = data$name,
          team = team
        )
    }) %>%
    bind_rows()
}
```

```{r theme, include=FALSE}
library(RColorBrewer)
base_theme <- theme_minimal()

theme_colors <- brewer.pal(4, "Set2")
names(theme_colors) <- c("green", "orange", "blue", "pink")
get_theme_color_values <- function(names) theme_colors[names] %>% unname()

scale_color_strategy <- scale_color_manual(
  "strategy",
  labels = c("diachronic", "synchronic"),
  values = get_theme_color_values(c("blue", "green"))
)

scale_color_team_label <- scale_color_manual(
  "skill overlap",
  labels = c("4 disjoint", "3", "2 overlapping", "1", "0 identical"),
  values = brewer.pal(7, "BuGn")[7:3]
)
scale_alpha_team <- scale_alpha_discrete(
  "skill overlap",
  labels = c("4 disjoint", "3", "2 overlapping", "1", "0 identical"),
  range = c(1.0, 0.1)
)
```

# Team structures

```{r team-structures, engine="dot", fig.width=2}
```

# Types of time

```{r types-of-time, fig.width = 3, fig.height = 3}
diachronic <- data_frame(
  strategy = "diachronic",
  calendar_hours = 0:100,
  labor_hours = calendar_hours
)

synchronic <- data_frame(
  strategy = "synchronic",
  calendar_hours = 0:50,
  labor_hours = calendar_hours * 2
)

time <- rbind(diachronic, synchronic)

axis_breaks <- c(0, 50, 100)
axis_labels <- c(0, expression(1/2), 1)

ggplot(time, aes(calendar_hours, labor_hours)) +
  geom_line(aes(color = strategy), size = 1.0) +
  scale_x_continuous("calendar hours", breaks = axis_breaks, labels = axis_labels) +
  scale_y_continuous("labor hours", breaks = axis_breaks, labels = axis_labels) +
  scale_color_strategy +
  base_theme +
  theme(legend.position = "top")
```

# Team abilities

```{r team-abilities}
teams <- get_experiment_data("differing-skills") %>%
  get_team_info() %>%
  gather(dimension, value, -c(team, player, team_id)) %>%
  recode_team() %>%
  select(-team)

legend_text <- data_frame(
  team_label_rev = factor(0, levels = 0:4),
  player = 1,
  value = c(0.1, 0.1),
  dimension = c("vision_x", "vision_y"),
  label = c("vision x", "vision y")
)

dodge_width <- position_dodge(width = 0.9)

ggplot(teams, aes(x = player, y = value, group = dimension)) +
  geom_bar(aes(fill = team_label_rev, alpha = dimension),
           stat = "identity", position = dodge_width) +
  facet_wrap("team_label_rev", nrow = 1) +
  geom_text(aes(label = label), data = legend_text, position = dodge_width,
         angle = 90, vjust = 0.4, hjust = 0) +
  scale_x_continuous(breaks = c(1, 2)) +
  scale_y_continuous("vision", breaks = 1:10, expand = c(0, 0)) +
  scale_fill_brewer(palette = "Set2") +
  scale_alpha_manual(values = c(0.5, 0.9)) +
  coord_cartesian(ylim = c(0, 9)) +
  base_theme +
  theme(
    legend.position = "none",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank()
  ) +
  labs(title = "Types of two person teams varying in skill distribution")
```

```{r, eval=FALSE}
ggplot(preds, aes(x = player, y = value, group = skill)) +
  geom_bar(aes(fill = team_ability, alpha = skill),
           stat = "identity", position = dodge_width) +
  facet_wrap("team_ability_label", nrow = 1) +
  scale_fill_brewer(palette = "Set2") +
  scale_alpha_manual(values = c(0.5, 0.9)) +
  geom_text(aes(label = label), data = legend_text, position = dodge_width,
            angle = 90, vjust = 0.5, hjust = 0) +
  base_theme +
  labs(title = "Types of two person teams varying in skill distribution")

t_range <- seq(0, 2 * pi, length.out = 100)
ellipse_x <- function(t, a, x0 = 0) x0 + a * cos(t)
ellipse_y <- function(t, b, y0 = 0) y0 + b * sin(t)

# Create a list of different area functions.
# Each fn returns data.frames with the same col names.
search_areas <- list(
  overlapping = function(player) {
    data_frame(
      player = player,
      team_ability = "identical",
      a = ellipse_x(t_range, 10),
      b = ellipse_y(t_range, 10)
    )
  },
  disjoint = function(player) {
    args <- list(
      x = list(a = 17, b = 3),
      y = list(a = 3, b = 17)
    )[[player]]
    data_frame(
      player = player,
      team_ability = "disjoint",
      a = ellipse_x(t_range, args[["a"]]),
      b = ellipse_y(t_range, args[["b"]])
    )
  },
  intersecting = function(player) {
    args <- list(
      x = list(a = 12, b = 8),
      y = list(a = 8, b = 12)
    )[[player]]
    data_frame(
      player = player,
      team_ability = "intersecting",
      a = ellipse_x(t_range, args[["a"]]),
      b = ellipse_y(t_range, args[["b"]])
    )
  }
)

spotlight_coords <- lapply(search_areas, function(area_fn) {
    # generate areas for players x and y and bind them together
    bind_rows(area_fn('x'), area_fn('y'))
  }) %>%
  # bind across area_fns
  bind_rows() %>%
  recode_team_abilities

legend_text <- data_frame(
  team_ability = "disjoint",
  player = c("x", "y"),
  a = c(10, 0),
  b = c(0, 10),
  label = c("player x", "player y"),
  angle = c(0, 90)
) %>%
  recode_team_abilities

ggplot(spotlight_coords, aes(a, b, group = player)) +
  geom_polygon(aes(fill = team_ability, alpha = player)) +
  facet_wrap("team_ability_label") +
  scale_fill_brewer(palette = "Set2") +
  scale_alpha_manual(values = c(0.5, 0.9)) +
  geom_text(aes(label = label, angle = angle), data = legend_text,
            vjust = 0.5) +
  base_theme +
  labs(title = "Abilities of two person teams as search areas in problem space")
```

# Identical team

```{r}
identical_team <- get_experiment_data("identical-team") %>%
  extract_position()

ggplot(identical_team) +
  aes(time, fitness_pct, color = strategy) +
  geom_line(stat = "summary", fun.y = "mean") +
  scale_x_continuous("calendar hours") +
  scale_y_continuous("fitness", labels = scales::percent) +
  scale_color_strategy +
  base_theme
```

```{r}
set.seed(782)
sample_sim_ids <- identical_team %>%
  group_by(strategy, starting_pos) %>%
  sample_n(1) %>%
  .$sim_id

random_walk_plot <- ggplot(identical_team) +
  aes(pos_x, pos_y, group = sim_id, color = strategy) +
  geom_path(alpha = 0.2) +
  annotate("point", x = 0, y = 0, shape = 4) +
  coord_equal() +
  facet_wrap("strategy") +
  labs(x = "x", y = "y") +
  scale_color_strategy +
  base_theme +
  theme(legend.position = "none")

random_walk_plot %+%
  filter(identical_team, sim_id %in% sample_sim_ids) +
  geom_path()

random_walk_plot
```

# Differing skills

```{r}
differing_skills <- get_experiment_data("differing-skills") %>%
  recode_team() %>%
  extract_position()

ggplot(differing_skills) +
  aes(time, fitness_pct, alpha = team_label, color = strategy) +
  geom_line(stat = "summary", fun.y = "mean") +
  scale_x_continuous("calendar hours") +
  scale_y_continuous("fitness", labels = scales::percent) +
  scale_color_strategy +
  scale_alpha_team +
  guides(color = guide_legend(order = 1),
         alpha = guide_legend(order = 2)) +
  base_theme
```

```{r}
(random_walk_plot %+% differing_skills) +
  facet_grid(strategy ~ team_label_rev)
```

# Solo teams

```{r}
solo_teams <- get_experiment_data("solo-teams") %>%
  recode_team()

ggplot(solo_teams) +
  aes(time, fitness_pct, alpha = team_label, color = strategy) +
  geom_line(stat = "summary", fun.y = "mean") +
  scale_x_continuous("calendar hours") +
  scale_y_continuous("fitness", labels = scales::percent) +
  scale_color_manual("strategy", values = get_theme_color_values(c("blue", "green"))) +
  scale_alpha_team +
  guides(color = guide_legend(order = 1),
         alpha = guide_legend(order = 2)) +
  base_theme
```

# Rate of alternation

```{r}
alternating <- get_experiment_data("alternating")

ggplot(alternating) +
  aes(time, fitness_pct, color = strategy) +
  geom_line(stat = "summary", fun.y = "mean") +
  scale_x_continuous("calendar hours") +
  scale_y_continuous("fitness", labels = scales::percent) +
  scale_color_strategy +
  base_theme
```

# Aggregate functions

```{r}
aggregate_fns <- get_experiment_data("aggregate-functions") 

ggplot(aggregate_fns) +
  aes(time, fitness_pct, color = aggregate_fn) +
  geom_line(stat = "summary", fun.y = "mean") +
  scale_color_brewer(palette = "Set2") +
  base_theme
```