---
title: "A continuous dimension of diachronic and synchronic strategies"
---

```{r config, include=FALSE}
library(knitr)
opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, results="hide")
sapply(list.files("../R", "*.R", full.names = TRUE), read_chunk)
```

```{r setup, include=FALSE}
```

## Labor hours and calendar hours

```{r time-plot, fig.width=4, fig.height=4}
diachronic <- data_frame(
  strategy = "diachronic",
  calendar_hours = 0:100,
  labor_hours = calendar_hours
)

synchronic <- data_frame(
  strategy = "synchronic",
  calendar_hours = 0:50,
  labor_hours = calendar_hours * 2
)

time <- rbind(diachronic, synchronic)

axis_breaks <- c(0, 50, 100)
axis_labels <- axis_breaks

(gg_time <- ggplot(time, aes(calendar_hours, labor_hours)) +
  geom_line(aes(color = strategy), size = 1.2) +
  scale_x_continuous("calendar hours", breaks = axis_breaks, labels = axis_labels) +
  scale_y_continuous("labor hours", breaks = axis_breaks, labels = axis_labels) +
  scale_color_strategy +
  guides(color = guide_legend(reverse = TRUE)) +
  base_theme +
  theme(legend.position = "top"))
```