---
title: "Omniscient mountain climbers"
output:
  html_document:
    theme: flatly
---

```{r config, include=FALSE}
library(knitr)
library(crotchet)
opts_chunk$set(echo=FALSE, message=FALSE, warning=FALSE, results='hide',
               cache=TRUE)
sapply(list.files("../R", "*.R", full.names = TRUE), read_chunk)
sapply(list.files("../gv", "*.gv", full.names = TRUE), read_graphviz_chunk)
```

```{r setup, include=FALSE}
```

```{r guessing-strategies, engine="dot", fig.width=5}
```

```{r omniscient}
data("omniscient")

omniscient %<>%
  recode_fitness_as_pct() %>%
  recode_strategy() %>%
  extract_position() %>%
  recode_team() %>%
  mutate(omniscient_label = factor(omniscient,
                                   levels = c(0, 1),
                                   labels = c("guessing", "omniscient")))

gg_omniscient_team_timeline <- ggplot(omniscient) +
  aes(time, fitness_pct, color = strategy, linetype = omniscient_label,
      group = interaction(strategy, omniscient_label)) +
  geom_line(stat = "summary", fun.y = "mean", size = 1.2) +
  scale_x_continuous("calendar hours") +
  scale_y_continuous("fitness", labels = scales::percent) +
  scale_color_manual(
    "",
    labels = c("diachronic", "synchronic"),
    values = get_theme_color_values(c("blue", "green")),
    guide = guide_legend(reverse = TRUE)
  ) +
  scale_linetype_discrete("", guide = guide_legend(reverse = TRUE)) +
  base_theme +
  theme(legend.position = "top")

max_fitness <- omniscient %>%
  group_by(sim_id, strategy, omniscient_label) %>%
  summarize(fitness_pct = max(fitness_pct)) %>%
  recode_strategy()

gg_omniscient_team_final_fitness <- ggplot(max_fitness) +
  aes(strategy_rev, fitness_pct) +
  geom_bar(aes(fill = strategy, alpha = omniscient_label),
           stat = "summary", fun.y = "mean") +
  geom_point(aes(color = strategy), alpha = 0.2,
             position = position_jitter(width = 0.2, height = 0.0),
             data = filter(max_fitness, omniscient_label == "Guessing")) +
  facet_wrap("omniscient_label") +
  coord_cartesian(ylim = c(0, 1)) +
  guides(alpha = "none", fill = "none", color = "none") +
  scale_x_strategy_rev +
  scale_y_fitness_pct +
  scale_color_manual(values = get_theme_color_values(c("blue", "green"))) +
  scale_fill_manual(values = get_theme_color_values(c("blue", "green"))) +
  scale_alpha_manual(values = c(0.8, 0.4)) +
  base_theme +
  theme(panel.grid.major.x = element_blank())

grid.arrange(gg_omniscient_team_timeline,
             gg_omniscient_team_final_fitness, nrow = 1)
```

# Differing skills

```{r}
gg_omniscient_team_timeline +
  aes(alpha = team_label, group = interaction(strategy, omniscient, team_label)) +
  scale_alpha_team +
  theme(legend.position = "right") +
  guides(alpha = guide_legend(reverse = FALSE))
```
