---
title: Vision as skill
output:
  html_document:
    theme: flatly
---

```{r config, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, cache = TRUE)
sapply(list.files("../R", "*.R", full.names = TRUE), knitr::read_chunk)
```

```{r setup, include=FALSE}
```

## Ability as vision

```{r, fig.width=6, fig.height=6}
ability <- data_frame(vision = 1:9)

gg_single_dimension <- ggplot(ability) +
  aes(vision, vision) +
  geom_bar(aes(alpha = vision), stat = "identity", fill = theme_colors[["blue"]]) +
  scale_x_continuous("", breaks = NULL) +
  scale_y_continuous("vision", breaks = 1:9) +
  scale_alpha_continuous(range = c(0.5, 1.0)) +
  guides(alpha = "none") +
  coord_cartesian(xlim = c(1, 9.2), ylim = c(0, 9.6)) +
  base_theme +
  theme(
    panel.grid.minor.y = element_blank()
  ) +
  ggtitle("Vision in a single dimension")


data("differing_skills")

teams <- differing_skills %>%
  get_team_info() %>%
  gather(dimension, value, -c(team, player, team_id)) %>%
  recode_team() %>%
  select(-team)

legend_text <- data_frame(
  team_label_rev = factor(0, levels = 0:4),
  player = 1,
  value = c(0.1, 0.1),
  dimension = c("vision_x", "vision_y"),
  label = c("vision x", "vision y")
)

dodge_width <- position_dodge(width = 0.9)

tradeoffs_plot <- ggplot() +
  aes(x = player, y = value, group = dimension) +
  geom_bar(aes(fill = team_label_rev, alpha = dimension),
           stat = "identity", position = dodge_width) +
  facet_wrap("team_label_rev", nrow = 1) +
  geom_text(aes(label = label), data = legend_text, position = dodge_width,
            angle = 90, vjust = 0.5, hjust = 0) +
  scale_x_continuous(breaks = c(1, 2)) +
  scale_y_continuous("vision", breaks = 1:10, expand = c(0, 0)) +
  scale_fill_brewer(palette = "Set2") +
  scale_alpha_manual(values = c(0.9, 0.5)) +
  coord_cartesian(ylim = c(0, 9)) +
  base_theme +
  theme(
    legend.position = "none",
    panel.grid.major.x = element_blank(),
    panel.grid.minor.x = element_blank(),
    panel.grid.minor.y = element_blank()
  )

gg_two_dimensions <- (tradeoffs_plot %+% filter(teams, player == 1)) +
  scale_x_continuous("", labels = NULL) +
  theme(strip.text = element_blank()) +
  labs(title = "Vision in two dimensions")

gg_differing_skills <- (tradeoffs_plot %+% teams) +
  labs(title = "Two person teams varying in vision distribution")

grid.arrange(
  arrangeGrob(gg_single_dimension, gg_two_dimensions, nrow = 1),
  gg_differing_skills,
  ncol = 1
)
```

## Vision and search areas

```{r, fig.width=8, fig.height=2}
# Vision of 1 gives a visible range of 3 (from -1 to 1)
visible_range <- function(vision) -vision:vision

# Vision in two dimensions is a search area
calculate_player_search_area <- function(vision_x, vision_y) {
  expand.grid(x = visible_range(vision_x),
              y = visible_range(vision_y))
}

player_search_areas <- data_frame(vision_x = 5:1, vision_y = 5:9) %>%
  rowwise() %>%
  do({
    areas <- calculate_player_search_area(.$vision_x, .$vision_y)
    areas[,c("vision_x", "vision_y")] <- c(.$vision_x, .$vision_y)
    areas$vision <- paste0("(", .$vision_x, ",", .$vision_y, ")")
    select(areas, vision, vision_x, vision_y, x, y)
  }) %>%
  ungroup() %>%
  mutate(
    # Technically these aren't teams
    team_label = factor(vision, levels = paste0("(", 5:1, ",", 5:9, ")"), labels = 0:4),
    team_label_rev = factor(vision, levels = rev(paste0("(", 5:1, ",", 5:9, ")")), labels = 0:4),
    centroid = ifelse(x == 0 & y == 0, TRUE, FALSE),
    pct_n = 1/n()
  )

player_search_areas_plot <- ggplot(player_search_areas) +
  aes(x = x, y = y, width = 0.9, height = 0.9,
      fill = team_label_rev) +
  geom_tile(aes(alpha = pct_n)) +
  scale_x_continuous("vision x", labels = NULL) +
  scale_y_continuous("vision y", labels = NULL) +
  scale_fill_brewer(palette = "Set2", guide = "none") +
  scale_alpha_continuous(range = c(0.2, 1.0), guide = "none") +
  coord_cartesian(xlim = c(-10, 10), ylim = c(-10, 10)) +
  facet_wrap("team_label_rev", nrow = 1, scales = "fixed") +
  base_theme +
  theme(
    strip.text = element_blank(),
    panel.grid = element_blank()
  )


calculate_team_search_area <- function(p1_vision_x, p1_vision_y,
                                       p2_vision_x, p2_vision_y) {
  expand.grid(
    p1_x = visible_range(p1_vision_x),
    p1_y = visible_range(p1_vision_y),
    p2_x = visible_range(p2_vision_x),
    p2_y = visible_range(p2_vision_y)
  ) %>% mutate(
    x = p1_x + p2_x,
    y = p1_y + p2_y
  ) %>%
    select(x, y)
}

team_search_areas <- data_frame(
    p1_vision_x = 5:1,
    p1_vision_y = 5:9,
    p2_vision_x = 5:9,
    p2_vision_y = 5:1
  ) %>%
  rowwise() %>%
  do({
    areas <- calculate_team_search_area(.$p1_vision_x, .$p1_vision_y,
                                        .$p2_vision_x, .$p2_vision_y)
    
    areas$team_label <- sprintf("(%s,%s)+(%s,%s)",
                                .$p1_vision_x, .$p1_vision_y, .$p2_vision_x, .$p2_vision_y)
    
    select(areas, team_label, x, y)
  }) %>%
  ungroup() %>%
  mutate(team_label = factor(team_label, labels = 4:0),
         team_label = factor(team_label, levels = 0:4)) %>%
  count(team_label, x, y) %>%
  group_by(team_label) %>%
  mutate(pct_n = n/n()) %>%
  ungroup()

team_search_areas_plot <- ggplot(team_search_areas) +
  aes(x = x, y = y, width = 0.9, height = 0.9,
      fill = team_label, alpha = pct_n) +
  geom_tile() +
  scale_x_continuous("vision x", labels = NULL) +
  scale_y_continuous("vision y", labels = NULL) +
  scale_fill_brewer(palette = "Set2", guide = "none") +
  scale_alpha_continuous(range = c(0.3, 1), guide = "none") +
  coord_cartesian(xlim = c(-10, 10), ylim = c(-10, 10)) +
  facet_wrap("team_label", nrow = 1, scales = "fixed") +
  base_theme +
  theme(
    strip.text = element_blank(),
    panel.grid = element_blank()
  )

search_areas <- bind_rows(
  player = select(player_search_areas, team_label, x, y),
  team = team_search_areas,
  .id = "search_area_type"
)

ggplot(search_areas) +
  aes(x = x, y = y, width = 0.9, height = 0.9,
      fill = team_label, alpha = pct_n) +
  geom_tile() +
  scale_x_continuous("vision x", labels = NULL) +
  scale_y_continuous("vision y", labels = NULL) +
  scale_fill_brewer(palette = "Set2", guide = "none") +
  scale_alpha_continuous(range = c(0.3, 1), guide = "none") +
  coord_cartesian(xlim = c(-10, 10), ylim = c(-10, 10)) +
  facet_grid(search_area_type ~ team_label) +
  base_theme +
  theme(
    strip.text = element_blank(),
    panel.grid = element_blank()
  )
```

```{r}
n_search_squares <- player_search_areas %>%
  group_by(vision_x, vision_y, vision, team_label, team_label_rev) %>%
  summarize(n_search_squares = n()) %>%
  ungroup()

ggplot(n_search_squares) +
  aes(team_label, n_search_squares, fill = team_label) +
  geom_bar(stat = "identity") +
  scale_x_discrete("(vision x, vision y)") +
  scale_y_continuous("n search squares") +
  scale_fill_brewer(palette = "Set2", guide = "none") +
  base_theme
```
